version: '3.6'

services:
  crebrid:
    container_name: "crebrid"
    image: "crebrid:latest"
    networks:
      - smartnet
    ports:
      - 65432:65432
    restart:
      on-failure
    enviroment:
      - SERVER_IP=192.168.178.32
      - SERVER_PORT=43123
      - ACCESS_CODE=3H34GJ67NH
  crebri:
    container_name: "crebri"
    image: crebri:latest
    networks:
      - smartnet
    restart:
      on-failure

networks:
  smartnet:
    driver: bridge
    
